# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.5"
manifest_format = "2.0"
project_hash = "87e72a69e0a93ddb8648af70d9cbcf8126f54bfb"

[[deps.Traction]]
path = "."
uuid = "c3884037-0468-47d5-91e9-e571122d0b79"
version = "0.1.0"
